knpu_oauth2_client:
  clients:
    github:
      type: github
      client_id: '%env(GITHUB_CLIENT_ID)%'
      client_secret: '%env(GITHUB_CLIENT_SECRET)%'
      redirect_route: security_github_connect_check
      redirect_params: {}
    google:
      type: google
      client_id: '%env(GOOGLE_CLIENT_ID)%'
      client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
      redirect_route: security_google_connect_check
      redirect_params: {}
    linkedin_2024:
      type: generic
      provider_class: App\Security\OAuth\LinkedIn\LinkedInProvider
      client_id: '%env(LINKEDIN_CLIENT_ID)%'
      client_secret: '%env(LINKEDIN_CLIENT_SECRET)%'
      redirect_route: security_linkedin_connect_check
      redirect_params: {}
