monolog:
    channels:
        - deprecation
        - google_oauth
        - error_controller

when@local:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!google_oauth", "!error_controller"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!google_oauth", "!error_controller"]
            google_oauth:
              type: stream
              path: "%kernel.logs_dir%/google-oauth-%kernel.environment%.log"
              level: debug
              channels: ["google_oauth"]
            error_controller:
              type: stream
              path: "%kernel.logs_dir%/error-controller-%kernel.environment%.log"
              level: debug
              channels: ["error_controller"]
          
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!google_oauth", "!error_controller"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!google_oauth", "!error_controller"]
            
            google_oauth:
              type: stream
              path: "%kernel.logs_dir%/google-oauth-%kernel.environment%.log"
              level: debug
              channels: ["google_oauth"]
            error_controller:
              type: stream
              path: "%kernel.logs_dir%/error-controller-%kernel.environment%.log"
              level: debug
              channels: ["error_controller"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
